frontend.enableClientVersionCheck:
  - value: true
    constraints: {}
system.enableGlobalDomain:
  - value: false
    constraints: {}
history.persistenceMaxQPS:
  - value: 3000
    constraints: {}
frontend.persistenceMaxQPS:
  - value: 3000
    constraints: {}
frontend.historyMgrNumConns:
  - value: 10
    constraints: {}
frontend.throttledLogRPS:
  - value: 20
    constraints: {}
history.historyMgrNumConns:
  - value: 50
    constraints: {}
system.advancedVisibilityWritingMode:
  - value: "off"
    constraints: {}
system.enableReadVisibilityFromES:
  - value: false
    constraints: {}
limit.maxIDLength:
  - value: 255
    constraints: {} 